Update package -> melinda-record-import-commons
NatLibFi/melinda-record-import-importer-dummy pull request #1
Opened 2019-09-16 09:40 UTC by natlibfi-jonollil

### Package update:
Melinda-record-import-commons: '^6.0.0'

### Local test settings:
- quay.io/natlibfi/melinda-record-import-api:test
- quay.io/natlibfi/melinda-record-import-controller:test
- melinda-record-import-importer-dummy #melkehitys-1023 build locally
- melinda-record-import-transformer-dummy #melkehitys-1023 build locally

2019-09-30 07:20 UTC, natlibfi-jonollil commented
Docker error
unauthorized: access to the requested resource is not authorized

2019-10-02 11:48 UTC, ghost requested changes
About the Docker unauthorized error: This repository had PRs enabled in Drone which caused the Docker-build stage (Builds triggered from PRs cannot access secrets by default).

2019-10-02 11:48 UTC, natlibfi-arlehiko commented on package.json
> +		"eslint-config-xo": "^0.27.1",
Should be `>=0.27.1 <1.0.0`

2019-10-02 11:48 UTC, natlibfi-arlehiko commented on src/import.js
> +		Logger.log('debug', 'Dummy importer! Dosent import records to Melinda');
Fix typo: `Dosent` -> `Doesn't`

2019-10-11 11:04 UTC, natlibfi-arlehiko commented
Great! Will merge when API, commons, controller and Helmet-transformer are ready.

2019-10-14 14:35 UTC, ghost requested changes
[@natlibfi/melinda-record-import-commons](https://www.npmjs.com/package/@natlibfi/melinda-record-import-commons/v/7.0.0) has been published. Update dependency to point to that version in NPM.

2019-10-25 06:52 UTC, ghost approved these changes

2019-10-25 06:52 UTC, merged